version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: unleash
      POSTGRES_USER: unleash
      POSTGRES_PASSWORD: unleash
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unleash"]
      interval: 10s
      timeout: 5s
      retries: 5

  unleash:
    image: unleashorg/unleash-server:latest
    environment:
      DATABASE_URL: postgres://unleash:unleash@postgres:5432/unleash
      DATABASE_SSL: "false"
      LOG_LEVEL: info
      INIT_FRONTEND_API_TOKENS: default:development.unleash-insecure-frontend-api-token
      INIT_CLIENT_API_TOKENS: default:development.unleash-insecure-client-api-token
    ports:
      - "4242:4242"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4242/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  unleash-edge:
    image: unleashorg/unleash-edge:latest
    command: edge
    environment:
      UPSTREAM_URL: http://unleash:4242
      TOKENS: "*:default:development.unleash-insecure-client-api-token"
      STRICT: false
      LOG_LEVEL: debug
    ports:
      - "3063:3063"
    depends_on:
      unleash:
        condition: service_healthy
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3063/internal-backstage/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  unleash-edge-frontend:
    image: unleashorg/unleash-edge:latest
    command: edge
    environment:
      UPSTREAM_URL: http://unleash:4242
      TOKENS: "*:default:development.unleash-insecure-client-api-token,*:default:development.unleash-insecure-frontend-api-token"
      STRICT: false
      LOG_LEVEL: debug
      APP_NAME: unleash-edge-frontend
      INSTANCE_ID: unleash-edge-frontend-1
      FEATURES_REFRESH_INTERVAL_SECONDS: 10
      METRICS_INTERVAL_SECONDS: 30
    ports:
      - "3064:3063"
    depends_on:
      unleash:
        condition: service_healthy
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3063/internal-backstage/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '4.0'
        reservations:
          memory: 256M
          cpus: '0.5'
